// <auto-generated />
namespace GDPRiS.Data.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dateModified_fix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dateModified_fix));
        
        string IMigrationMetadata.Id
        {
            get { return "201807101528307_dateModified_fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
